import type { BlogPost, Resource } from "./strapi";
import type { Locale } from "./i18n/types";

const MOCK_BLOG_POSTS_AR: BlogPost[] = [
  {
    id: 1,
    title: "سر نايك الذي تجاهلوه: لماذا التركيز أهم من التوسع؟",
    slug: "nike-focus-strategy",
    excerpt: "كيف يساعدك التمركز على شريحة واحدة على بناء علامة استشارية قوية.",
    content: `<p>التركيز ليس قيداً—بل ميزة تنافسية للمستشارين والخبراء.</p>
<h2>حدّد شريحتك</h2><p>ابدأ بمن تخدمهم أفضل، لا بمن يدفعون أسرع.</p>`,
    author: "نبيل",
    category: "الاستراتيجية والتمركز",
    readTime: 6,
    publishedAt: "2026-04-12T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 2,
    title: "بناء الفريق في عصر الذكاء الاصطناعي",
    slug: "team-building-ai-era",
    excerpt: "كيف توظّف وتدير فريقاً صغيراً يحقق نتائج كبيرة.",
    content: `<p>الفريق الصغير المتخصص يتفوق على الهيكل الكبير في المشاريع الاستشارية.</p>`,
    author: "نبيل",
    category: "بناء المشروع والمنتجات",
    readTime: 5,
    publishedAt: "2026-03-28T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 3,
    title: "من الخدمة إلى المنتج: كيف تبيع خبرتك",
    slug: "sell-expertise-not-hours",
    excerpt: "إطار عملي لتحويل الاستشارة إلى منتجات رقمية قابلة للتوسع.",
    content: `<p>الخبرة المُعبأة في منتج تُحرر وقتك وتضاعف الدخل.</p>`,
    author: "نبيل",
    category: "النمو والتسويق",
    readTime: 4,
    publishedAt: "2026-03-15T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 4,
    title: "تصميم صفحة هبوط تحوّل الزوار إلى عملاء",
    slug: "landing-page-conversion",
    excerpt: "عناصر الصفحة التي ترفع معدل التحويل دون تعقيد.",
    content: `<p>الوضوح، الدليل الاجتماعي، وCTA واحد—ثلاثية النجاح.</p>`,
    author: "نبيل",
    category: "النمو والتسويق",
    readTime: 5,
    publishedAt: "2026-02-20T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 5,
    title: "عقلية المؤسس: الانتقال من مستشار إلى رائد أعمال",
    slug: "founder-mindset",
    excerpt: "التغييرات الذهنية اللازمة لبناء مشروع مستدام.",
    content: `<p>أنت تبني نظاماً، لا تبيع ساعاتاً.</p>`,
    author: "نبيل",
    category: "العقلية والتحفيز",
    readTime: 4,
    publishedAt: "2026-02-01T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 6,
    title: "كيف تُسعّر باقاتك الاستشارية بثقة",
    slug: "pricing-consulting-packages",
    excerpt: "نموذج تسعير يعكس قيمتك ويجذب العملاء المناسبين.",
    content: `<p>السعر رسالة—اجعلها واضحة ومتسقة مع وعدك.</p>`,
    author: "نبيل",
    category: "العملاء والمبيعات",
    readTime: 6,
    publishedAt: "2026-01-15T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 7,
    title: "نشرة بريدية تبني علاقة قبل البيع",
    slug: "newsletter-before-selling",
    excerpt: "كيف تكتب نشرة يقرأها متابعوك فعلاً.",
    content: `<p>القيمة أولاً، العرض ثانياً—دائماً.</p>`,
    author: "نبيل",
    category: "النمو والتسويق",
    readTime: 5,
    publishedAt: "2025-12-10T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 8,
    title: "أتمتة المحتوى دون فقدان الأصالة",
    slug: "content-automation-authentic",
    excerpt: "أدوات وعمليات تحافظ على صوتك الشخصي.",
    content: `<p>الأتمتة تدعم الإبداع—لا تستبدله.</p>`,
    author: "نبيل",
    category: "الإنتاجية والعادات",
    readTime: 4,
    publishedAt: "2025-11-22T10:00:00.000Z",
    coverImage: null,
  },
];

const MOCK_BLOG_POSTS_EN: BlogPost[] = [
  {
    id: 1,
    title: "The Nike secret they ignored: why focus beats expansion",
    slug: "nike-focus-strategy",
    excerpt: "How narrowing to one audience builds a stronger consulting brand.",
    content: `<p>Focus isn't a constraint—it's a competitive advantage for consultants and experts.</p>
<h2>Define your niche</h2><p>Start with who you serve best, not who pays fastest.</p>`,
    author: "Nabeel",
    category: "Strategy & positioning",
    readTime: 6,
    publishedAt: "2026-04-12T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 2,
    title: "Building a team in the age of AI",
    slug: "team-building-ai-era",
    excerpt: "How to hire and lead a small team that delivers outsized results.",
    content: `<p>A small specialist team beats a large hierarchy on consulting projects.</p>`,
    author: "Nabeel",
    category: "Product building",
    readTime: 5,
    publishedAt: "2026-03-28T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 3,
    title: "From service to product: how to sell your expertise",
    slug: "sell-expertise-not-hours",
    excerpt: "A practical framework for turning consulting into scalable digital products.",
    content: `<p>Packaged expertise frees your time and multiplies income.</p>`,
    author: "Nabeel",
    category: "Growth & marketing",
    readTime: 4,
    publishedAt: "2026-03-15T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 4,
    title: "Landing pages that turn visitors into clients",
    slug: "landing-page-conversion",
    excerpt: "The elements that lift conversion without adding complexity.",
    content: `<p>Clarity, social proof, and one CTA—the winning trio.</p>`,
    author: "Nabeel",
    category: "Growth & marketing",
    readTime: 5,
    publishedAt: "2026-02-20T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 5,
    title: "Founder mindset: from consultant to entrepreneur",
    slug: "founder-mindset",
    excerpt: "The mental shifts required to build a sustainable business.",
    content: `<p>You're building a system, not selling hours.</p>`,
    author: "Nabeel",
    category: "Mindset & motivation",
    readTime: 4,
    publishedAt: "2026-02-01T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 6,
    title: "How to price your consulting packages with confidence",
    slug: "pricing-consulting-packages",
    excerpt: "A pricing model that reflects your value and attracts ideal clients.",
    content: `<p>Price is a message—make it clear and aligned with your promise.</p>`,
    author: "Nabeel",
    category: "Clients & sales",
    readTime: 6,
    publishedAt: "2026-01-15T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 7,
    title: "A newsletter that builds trust before the sale",
    slug: "newsletter-before-selling",
    excerpt: "How to write emails your audience actually reads.",
    content: `<p>Value first, offer second—always.</p>`,
    author: "Nabeel",
    category: "Growth & marketing",
    readTime: 5,
    publishedAt: "2025-12-10T10:00:00.000Z",
    coverImage: null,
  },
  {
    id: 8,
    title: "Automating content without losing authenticity",
    slug: "content-automation-authentic",
    excerpt: "Tools and workflows that keep your personal voice.",
    content: `<p>Automation should support creativity—not replace it.</p>`,
    author: "Nabeel",
    category: "Productivity & habits",
    readTime: 4,
    publishedAt: "2025-11-22T10:00:00.000Z",
    coverImage: null,
  },
];

const MOCK_RESOURCES_AR: Resource[] = [
  {
    id: 1,
    title: "دليل استراتيجية العلامة ٢٠٢٦",
    description: "٢٤ صفحة عن التمركز والرسالة وخطة الإطلاق.",
    category: "Guide",
    featured: true,
    downloadCount: 1284,
    file: null,
  },
  {
    id: 2,
    title: "قائمة فحص إطلاق الموقع",
    description: "SEO، الأداء، إمكانية الوصول، والتحويل.",
    category: "Checklist",
    featured: false,
    downloadCount: 892,
    file: null,
  },
  {
    id: 3,
    title: "حزمة قوالب الانضمام للعملاء",
    description: "عرض، اجتماع انطلاق، واستبيان اكتشاف.",
    category: "Template",
    featured: false,
    downloadCount: 654,
    file: null,
  },
];

const MOCK_RESOURCES_EN: Resource[] = [
  {
    id: 1,
    title: "2026 Brand Strategy Playbook",
    description: "24 pages on positioning, messaging, and launch planning.",
    category: "Guide",
    featured: true,
    downloadCount: 1284,
    file: null,
  },
  {
    id: 2,
    title: "Website Launch Checklist",
    description: "SEO, performance, accessibility, and conversion essentials.",
    category: "Checklist",
    featured: false,
    downloadCount: 892,
    file: null,
  },
  {
    id: 3,
    title: "Client Onboarding Template Pack",
    description: "Proposal, kickoff agenda, and discovery questionnaire.",
    category: "Template",
    featured: false,
    downloadCount: 654,
    file: null,
  },
];

export function getMockBlogPosts(locale: Locale): BlogPost[] {
  return locale === "en" ? MOCK_BLOG_POSTS_EN : MOCK_BLOG_POSTS_AR;
}

export function getMockResources(locale: Locale): Resource[] {
  return locale === "en" ? MOCK_RESOURCES_EN : MOCK_RESOURCES_AR;
}

/** @deprecated use getMockBlogPosts(locale) */
export const MOCK_BLOG_POSTS = MOCK_BLOG_POSTS_AR;
/** @deprecated use getMockResources(locale) */
export const MOCK_RESOURCES = MOCK_RESOURCES_AR;
